---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the behavior you observed.
      placeholder: "Example: I ran `pants fmt ::` and it <some bad or unexpected behavior>."
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What was expected?
      description: Tell us what you expected to happen instead.
      placeholder: "Example: When running `pants fmt ::`, it should have <expected action>"
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin and version
      description: Which plugin are you running, and at what version? Please specify fully (<major>.<minor>.<patch>).
      placeholder: pyproject-fmt-pants-plugin 0.1.0
    validations:
      required: true
  - type: input
    id: pants-version
    attributes:
      label: Pants version
      description: The `pants_version` from your `pants.toml`.
      placeholder: 2.33.1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code,
        so no need for backticks.
      render: shell
