---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: Feature Request
description: Request a new feature.
title: "[Feature]: "
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feature request.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A short description of the feature you would like added to the plugin.
      placeholder: |
        Rather than describing implementation details for this feature, try to describe what you are trying to achieve.
    validations:
      required: true
  - type: textarea
    id: related-issues
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
      placeholder: "Related: zach-overflow/pants-plugin-depot/issues/<Issue number here>"
