resource(name="py-typed-marker", source="py.typed")
resource(name="plugin-test-utils-lockfile", source="pants_plugin_developer_utils.json")
python_sources(dependencies=[":plugin-test-utils-lockfile", ":py-typed-marker"])
